appName: actions-runner

runnerImage: quay.io/redhat-github-actions/redhat-actions-runner
runnerTag: v0.1
imagePullPolicy: Always

githubOwner: ""
githubRepository: ""

# The name of the k8s secret to create.
secretName: "github-pat"
# The name of the key that points to the data within the secret.
# Modify this to store multiple PATs in one secret.
secretKey: "github-pat"
# The PAT itself - must be set if the secret is being created.
githubPat: ""

# Pass labels comma-delimited. If setting through the helm command line, commas must be escaped.
# --set runnerLabels="label1\,label2" results in the labels "label1" and "label2".
runnerLabels: ""

# Adjust replicas and limits accordingly, depending on your resources available,
# how many jobs you want to run concurrently,
# and how much processing power your workflows require.
replicas: 1
memoryLimit: "1Gi"
cpuLimit: "500m"

# If you have administrator privileges and understand the security implications of privileged containers,
# set this to true to easily get buildah and podman working, among other things.
# Running as root is still not allowed by the deploy,ent.
privileged: false

# You can inject arbitrary environment variables here:
runnerEnv:
    # - name: ENV_VAR
    #   value: env_value
    # or, through the command line:
    # --set runnerEnv[0].name="ENV_VAR" --set runnerEnv[0].value="env_value"
